### PR TITLE
Calendar functions

### PR DESCRIPTION
**Pull request by mhokanson**
I've written a few functions for interacting with exchange calendars, as well as adding a function for deleting items without requiring users to confirm.

It looks like you've added 'EXR' to a lot of your functions since I wrote these functions. I can update my function names if you want to adopt them.

### CODE REVIEW

**Comment by mhokanson** [comment]
Also, as this is my first foray into contributing to a project, if there are any things I should change in how I issue pull requests, please feel free to enlighten me.

**Comment by gscales** [comment]
Thanks for the contribution it looks great, I'll integrate into the new code base as I've also changed some of the token access methods to make it more user friendly and reliable. The only thing I would say to make the contribution better in the future is include some samples of the cmdlet being used (although I'm really bad at that as well) but this will help people who want to do similar things with the module.

**Comment by gscales** [comment]
One other thing is for debugging you can now use

Set-ExrTracing -Tracing:$true

Which will output the REST string to the console which is a better way then using Write-host in the cmdlet

**Comment by mhokanson** [comment]
Great! Thanks!

**Pull request merged**
